SET(THIS_LIB_NAME QtUtility)
SET(THIS_THIRDPART_DIR ThirdPart)
SET(THIS_INCLUDE_FILE_NAME QU_global.h)

IF(USE_THIS_PRJ_THIRDPART)
	SET(ENV{THIS_ENVIRONMENT_NAME} ${PROJECT_SOURCE_DIR}/${THIS_THIRDPART_DIR}/${THIS_LIB_NAME})
	SET(THIS_LIB_DIR $ENV{THIS_ENVIRONMENT_NAME})
ELSE(USE_THIS_PRJ_THIRDPART)
	SET(THIS_ENVIRONMENT_NAME ${THIS_LIB_NAME}_ROOT)
	SET(THIS_LIB_DIR $ENV{${THIS_ENVIRONMENT_NAME}})
ENDIF(USE_THIS_PRJ_THIRDPART)

MESSAGE("===========Begin FindPackage[${THIS_LIB_NAME}] In Folder ${THIS_LIB_DIR}==============")

FIND_PATH(${THIS_LIB_NAME}_INCLUDE_DIR ${THIS_INCLUDE_FILE_NAME}
PATHS
    ${THIS_LIB_DIR}/include
)

FIND_LIBRARY(${THIS_LIB_NAME}_LIBRARY
  NAMES ${THIS_LIB_NAME}
  PATHS
  "${THIS_LIB_DIR}/lib"
)

FIND_LIBRARY(${THIS_LIB_NAME}_LIBRARY_DEBUG
  NAMES ${THIS_LIB_NAME}d
  PATHS
  "${THIS_LIB_DIR}/lib"
)

SET(THIS_LIB_FOUND "NO")
IF(${THIS_LIB_NAME}_LIBRARY AND ${THIS_LIB_NAME}_INCLUDE_DIR)
    SET(THIS_LIB_FOUND "YES")
	MESSAGE("===========Finish FindPackage[${THIS_LIB_NAME}].....")
ELSE(${THIS_LIB_NAME}_LIBRARY AND ${THIS_LIB_NAME}_INCLUDE_DIR)
	MESSAGE(FATAL "===========FindPackage[${THIS_LIB_NAME}] Failed!.....")
ENDIF(${THIS_LIB_NAME}_LIBRARY AND ${THIS_LIB_NAME}_INCLUDE_DIR)