#this file decript some variable of the cmake_module_path, it help some function or macro auto include, you can add path use APPEND_CMAKE_MODULE_PATH macro.

MACRO(APPEND_CMAKE_MODULE_PATH path)
    LIST(APPEND CMAKE_MODULE_PATH ${path})
    LIST(REMOVE_DUPLICATES CMAKE_MODULE_PATH)
    #MESSAGE(STATUS "CMAKE_MODULE_PATH = ${CMAKE_MODULE_PATH}")
ENDMACRO()

SET(THIS_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR})
#MESSAGE(STATUS "THIS_MODULE_PATH = ${THIS_MODULE_PATH}")

SET(THIS_MODULE_RESOURCE_PATH ${THIS_MODULE_PATH}/resource)
#MESSAGE(STATUS "THIS_MODULE_RESOURCE_PATH = ${THIS_MODULE_RESOURCE_PATH}")

SET(THIS_MODULE_TEMPLATES_PATH ${THIS_MODULE_PATH}/Templates)
#MESSAGE(STATUS "THIS_MODULE_TEMPLATES_PATH = ${THIS_MODULE_TEMPLATES_PATH}")

#append macrofunc subdirs with some utils or macros
APPEND_CMAKE_MODULE_PATH(${PROJECT_SOURCE_DIR})

APPEND_CMAKE_MODULE_PATH(${THIS_MODULE_PATH}/utils)

APPEND_CMAKE_MODULE_PATH(${THIS_MODULE_PATH}/macrofunc)

APPEND_CMAKE_MODULE_PATH(${THIS_MODULE_PATH}/find_module)

APPEND_CMAKE_MODULE_PATH(${THIS_MODULE_PATH}/check_module)


