include(macro_decide_install_dir)
#============================================
OPTION(THIRD_PARTH_LIBARARY_OUTPUT "Enalbe THIRD_PARTH_LIBARARY_OUTPUT" OFF)
UNSET(THIRD_PARTH_LIBARARY_OUTPUT_PATH)
SET(THIRD_PARTH_LIBARARY_OUTPUT_PATH ${PROJECT_BINARY_DIR})

IF(THIRD_PARTH_LIBARARY_OUTPUT)
    UNSET(THIRD_PARTH_LIBARARY_OUTPUT_PATH)
    SET(THIRD_PARTH_LIBARARY_OUTPUT_PATH ${PROJECT_BINARY_DIR} CACHE PATH "Set The Output Dir!!!")

    IF(NOT THIRD_PARTH_LIBARARY_OUTPUT_DIR)
      SET(THIRD_PARTH_LIBARARY_OUTPUT_DIR ThirdParty CACHE STRING "Set The Install Dir! Default Is 'ThirdParty'")
    ENDIF()

    IF(NOT EXISTS ${THIRD_PARTH_LIBARARY_OUTPUT_PATH})
        MESSAGE(FATAL_ERROR "There Is No THIRD_PARTH_LIBARARY_OUTPUT_PATH With: ${THIRD_PARTH_LIBARARY_OUTPUT_PATH}, You Must Set The THIRD_PARTH_LIBARARY_OUTPUT_PATH On CMake UI By Yourself!!!!")
    ENDIF()

    UNSET(CMAKE_INSTALL_PREFIX CACHE)
    SET(CMAKE_INSTALL_PREFIX ${THIRD_PARTH_LIBARARY_OUTPUT_PATH}/${THIRD_PARTH_LIBARARY_OUTPUT_DIR} CACHE PATH "The Install Path...")
ENDIF(THIRD_PARTH_LIBARARY_OUTPUT)

SET(THIRD_PARTH_LIBARARY_OUTPUT_BIN_DIR ${THIRD_PARTH_LIBARARY_OUTPUT_PATH}/bin)
SET(THIRD_PARTH_LIBARARY_OUTPUT_LIB_DIR ${THIRD_PARTH_LIBARARY_OUTPUT_PATH}/lib)
MAKE_DIRECTORY(${THIRD_PARTH_LIBARARY_OUTPUT_LIB_DIR})
MAKE_DIRECTORY(${THIRD_PARTH_LIBARARY_OUTPUT_BIN_DIR})

MESSAGE(STATUS "::THIRD_PARTH_LIBARARY_OUTPUT_BIN_DIR: ${THIRD_PARTH_LIBARARY_OUTPUT_BIN_DIR}")
MESSAGE(STATUS "::THIRD_PARTH_LIBARARY_OUTPUT_LIB_DIR: ${THIRD_PARTH_LIBARARY_OUTPUT_LIB_DIR}")
MESSAGE(STATUS "CMAKE_CXX_FLAGES_DEBUG::::::${CMAKE_CXX_FLAGES_DEBUG}")

UNSET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY)
UNSET(CMAKE_RUNTIME_OUTPUT_DIRECTORY)
UNSET(CMAKE_LIBRARY_OUTPUT_DIRECTORY)
SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${THIRD_PARTH_LIBARARY_OUTPUT_LIB_DIR})
SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${THIRD_PARTH_LIBARARY_OUTPUT_BIN_DIR})
SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${THIRD_PARTH_LIBARARY_OUTPUT_BIN_DIR})

SET(_RUNTIME_OUTPUT_DIRECTORY_DEBUG "${THIRD_PARTH_LIBARARY_OUTPUT_PATH}/bin/debug")
SET(_RUNTIME_OUTPUT_DIRECTORY_RELEASE "${THIRD_PARTH_LIBARARY_OUTPUT_PATH}/bin/release")
#==============================================================
MACRO(LIBRARY_SET_PROPERTIES_OUTPUT target)
    SET_TARGET_PROPERTIES(${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY  "${THIRD_PARTH_LIBARARY_OUTPUT_PATH}" )
    SET_TARGET_PROPERTIES(${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY_DEBUG ${_RUNTIME_OUTPUT_DIRECTORY_DEBUG} )
    SET_TARGET_PROPERTIES(${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY_RELEASE ${_RUNTIME_OUTPUT_DIRECTORY_RELEASE})
    MESSAGE(STATUS "::_RUNTIME_OUTPUT_DIRECTORY_DEBUG: ${_RUNTIME_OUTPUT_DIRECTORY_DEBUG}")
    MESSAGE(STATUS "::_RUNTIME_OUTPUT_DIRECTORY_RELEASE: ${_RUNTIME_OUTPUT_DIRECTORY_RELEASE}") 
ENDMACRO()
#==============================================================
MACRO(INSTALL_PDB_FILE target)

    IF(${CMAKE_BUILD_TYPE} MATCHES "Debug")
        set(pdb_file_name ${target}${CMAKE_DEBUG_POSTFIX}.pdb)
        INSTALL(FILES ${_RUNTIME_OUTPUT_DIRECTORY_DEBUG}/${pdb_file_name}
            DESTINATION ${${target}_INSTALL_RUNTIME})
    ELSE()
        set(pdb_file_name ${target}${CMAKE_RELEASE_POSTFIX}.pdb)
        INSTALL(FILES ${_RUNTIME_OUTPUT_DIRECTORY_RELEASE}/${pdb_file_name}
            DESTINATION ${${target}_INSTALL_RUNTIME})
    ENDIF()
ENDMACRO()

