#============================================

OPTION(VRPROJECT_OUTPUT "Enalbe VRProject_OutPut" OFF)

SET(VRPROJECT_OUTPUT_DIR ${PROJECT_SOURCE_DIR})

IF(VRPROJECT_OUTPUT)
    UNSET(VRPROJECT_OUTPUT_DIR)
    SET(VRPROJECT_OUTPUT_DIR ${PROJECT_SOURCE_DIR} CACHE PATH "Set The Output Dir!!!")
    
    IF(NOT EXISTS ${VRPROJECT_OUTPUT_DIR})
        MESSAGE(FATAL_ERROR "There Is No VRPROJECT_OUTPUT_DIR With: ${VRPROJECT_OUTPUT_DIR}, You Must Set The VRPROJECT_OUTPUT_DIR On CMake UI By Yourself!!!!")
    ENDIF()

    UNSET(CMAKE_INSTALL_PREFIX CACHE)
    #这里都用固定的目录VRE3Frame
    SET(CMAKE_INSTALL_PREFIX ${VRPROJECT_OUTPUT_DIR}/VRE3Frame CACHE PATH "The VRE3Frame Install Dir.....")
ENDIF(VRPROJECT_OUTPUT)

SET(OUTPUT_BINDIR ${VRPROJECT_OUTPUT_DIR}/bin)
SET(OUTPUT_LIBDIR ${VRPROJECT_OUTPUT_DIR}/lib)
MESSAGE(STATUS "OUTPUT_BINDIR: ${OUTPUT_BINDIR}")
MESSAGE(STATUS "OUTPUT_LIBDIR: ${OUTPUT_LIBDIR}")

MAKE_DIRECTORY(${OUTPUT_LIBDIR})
MAKE_DIRECTORY(${OUTPUT_BINDIR})

UNSET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY)
UNSET(CMAKE_RUNTIME_OUTPUT_DIRECTORY)
UNSET(CMAKE_LIBRARY_OUTPUT_DIRECTORY)
SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${OUTPUT_LIBDIR})
SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${OUTPUT_BINDIR})
SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${OUTPUT_BINDIR})

MACRO(SET_PROPERTIES_OUTPUT target)
    SET_TARGET_PROPERTIES(${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY  "${VRPROJECT_OUTPUT_DIR}" )
    SET_TARGET_PROPERTIES(${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY_DEBUG "${VRPROJECT_OUTPUT_DIR}/bin/debug" )
    SET_TARGET_PROPERTIES(${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY_RELEASE "${VRPROJECT_OUTPUT_DIR}/bin/release") 
ENDMACRO()

#============================================

MACRO(INSTALL_VRFRAME_LIB target)
    MESSAGE(STATUS "Begin Install the ${target}....")

    INSTALL(CODE "MESSAGE(\"Installing ${target}  ...\")")

    SET(lib_include ${PROJECT_SOURCE_DIR}/include/${target})
    INSTALL(DIRECTORY ${lib_include}/ DESTINATION include/${target})

    INSTALL(
       TARGETS ${target}
       RUNTIME DESTINATION bin
       LIBRARY DESTINATION lib
       ARCHIVE DESTINATION lib
    )
ENDMACRO()

MACRO(INSTALL_VRER3FRAME_LIB target)
   INSTALL_VRFRAME_LIB(${target})
ENDMACRO()

#============================================
MACRO(INSTALL_VRE3FRAME_BSPLUGIN)
    INSTALL(
       TARGETS ${LIB_NAME}
       RUNTIME DESTINATION bin/VRPlugins/BSPlugins/
       LIBRARY DESTINATION lib
       ARCHIVE DESTINATION lib
    )
ENDMACRO()
#============================================
MACRO(INSTALL_VRE3FRAME_ACTORPLUGIN)
    INSTALL(
       TARGETS ${LIB_NAME}
       RUNTIME DESTINATION bin/VRPlugins/ActorPlugins
       LIBRARY DESTINATION lib
       ARCHIVE DESTINATION lib
       ) 
ENDMACRO()
#============================================
MACRO(SET_PROPERTIES_OUTPUT_BSPLUGIN target)
    SET_TARGET_PROPERTIES( ${LIB_NAME} PROPERTIES RUNTIME_OUTPUT_DIRECTORY  "${VRPROJECT_OUTPUT_DIR}/bin/VRPlugins/BSPlugins" )
    SET_TARGET_PROPERTIES( ${LIB_NAME} PROPERTIES RUNTIME_OUTPUT_DIRECTORY_DEBUG "${VRPROJECT_OUTPUT_DIR}/bin/debug/VRPlugins/BSPlugins" )
    SET_TARGET_PROPERTIES( ${LIB_NAME} PROPERTIES RUNTIME_OUTPUT_DIRECTORY_RELEASE "${VRPROJECT_OUTPUT_DIR}/bin/release/VRPlugins/BSPlugins") 
ENDMACRO()

MACRO(SET_PROPERTIES_OUTPUT_ACTORPLUGIN target)
#输出到上级目录，取消debug, release 目录
    SET_TARGET_PROPERTIES( ${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY  "${VRPROJECT_OUTPUT_DIR}/bin/VRPlugins/ActorPlugins" )
    SET_TARGET_PROPERTIES( ${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY_DEBUG "${VRPROJECT_OUTPUT_DIR}/bin/debug/VRPlugins/ActorPlugins" )
    SET_TARGET_PROPERTIES( ${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY_RELEASE "${VRPROJECT_OUTPUT_DIR}/bin/release/VRPlugins/ActorPlugins") 
ENDMACRO()

