
MACRO(SET_EXCUTABLE_PROPERTIES _target)
	if(NOT TARGET ${_target})
		MESSAGE(FATAL_ERROR "SET_EXCUTABLE_PROPERTIES With Invalide Target.....")
	endif()

   IF(WIN32)
		SET_TARGET_PROPERTIES(${_target} PROPERTIES
			if(${ProjectVal_PREFIX_CONFIG}_EXCUTABLE_RELEASE_WITH_CONSOLE)
				LINK_FLAGS_RELEASE "/SUBSYSTEM:CONSOLE"
			else()
				LINK_FLAGS_RELEASE "/ENTRY:\"mainCRTStartup\" /SUBSYSTEM:WINDOWS"
			endif()
			#LINK_FLAGS "/VERSION:${APPLICATION_VERSION}"
			LINK_FLAGS_DEBUG "/SUBSYSTEM:CONSOLE" 
		)
	ENDIF(WIN32)
ENDMACRO()

OPTION(${ProjectVal_PREFIX_CONFIG}_EXCUTABLE_RELEASE_WITH_CONSOLE "Set to ON nd packaging targets" OFF)