#================QtMacros Include============================
include(macro_target_process_qt_resources_uis)
#============================================================
macro(qt_support)
    IF(CMAKE_CL_64)
        COMMON_GET_ENV(_QT_DIR QTDIR_64)
        if(NOT EXISTS ${_QT_DIR})
            SET(QT_QTDIR_64 "" CACHE PATH "")
            IF(NOT EXISTS ${QT_QTDIR_64})
                MESSAGE(FATAL_ERROR "Invalide Qtx64 Dir...")
            ELSE()
                SET(_QT_DIR ${QT_QTDIR_64})
            ENDIF()
        endif()
    ELSE()
        COMMON_GET_ENV(_QT_DIR QTDIR_32)
        if(NOT EXISTS ${_QT_DIR})
            SET(QT_QTDIR_32 "" CACHE PATH "")
            IF(NOT EXISTS ${QT_QTDIR_32})
                MESSAGE(FATAL_ERROR "Invalide Qtx86 Dir...")
            ELSE()
                SET(_QT_DIR ${QT_QTDIR_32})
            ENDIF()
        endif()
    ENDIF()

    set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} ${_QT_DIR})


    #MESSAGE(STATUS ":::::::::::::qt_support...")
    FIND_PACKAGE(Qt5Core REQUIRED)
    FIND_PACKAGE(Qt5Widgets REQUIRED)
    FIND_PACKAGE(Qt5Gui REQUIRED)
    IF ( Qt5Core_FOUND AND Qt5Widgets_FOUND AND Qt5Gui_FOUND)
        SET(QT_INCLUDES ${Qt5Widgets_INCLUDE_DIRS} ${Qt5OpenGL_INCLUDE_DIRS})
        SET(QT_ALL_LIBRARIES ${QT_LIBRARIES} ${QT_QTCORE_LIBRARY} ${QT_QTWEBKIT_LIBRARY} ${QT_QTNETWORK_LIBRARY} ${QT_QTXML_LIBRARY} ${QT_QTOPENGL_LIBRARY})
        SET(QT5_FOUND ON)
        MESSAGE(STATUS ":::::::::::::qt_support:QT5_FOUND")
    ELSE()
        FIND_PACKAGE(Qt4)
        IF (QT4_FOUND)
            INCLUDE(${QT_USE_FILE})
            SET(QT_INCLUDES ${QT_INCLUDES} ${QT_INCLUDE_DIR} ${QT_QTCORE_INCLUDE_DIR} ${QT_QTGUI_INCLUDE_DIR}${QT_QTOPENGL_INCLUDE_DIR} )
            SET(QT_ALL_LIBRARIES ${QT_LIBRARIES} ${QT_QTCORE_LIBRARY} ${QT_QTWEBKIT_LIBRARY} ${QT_QTNETWORK_LIBRARY} ${QT_QTXML_LIBRARY} ${QT_QTOPENGL_LIBRARY})
            MESSAGE(STATUS ":::::::::::::qt_support:QT4_FOUND")
        ENDIF (QT4_FOUND)
    ENDIF ()

    IF(NOT QT5_FOUND AND NOT QT4_FOUND)
        MESSAGE(FATAL_ERROR ":::::::::::::qt_support:no found qt!!!!")
    ENDIF()

    SET(QT_SUPPORT TRUE)
    SET(QT_DIR ${_QT_DIR})
endmacro()


macro(USE_QT)
    qt_support(${ARGN})
endmacro()

