include(macro_target_process_qt_resources_uis)

MACRO(VIRE_TARGET_PROCESS_QT_RESOURCES_UIS target_name)
    TARGET_PROCESS_QT_RESOURCES_UIS(${target_name})
ENDMACRO()

MACRO(VIRE_PROCESS_QT_RESOURCES_UIS _lib)
    TARGET_PROCESS_QT_RESOURCES_UIS(${_lib})
ENDMACRO()

MACRO(VIRE_PROCESS_QT_RESOURCES_UIS)
    TARGET_PROCESS_QT_RESOURCES_UIS(${LIB_NAME})
ENDMACRO()

MACRO(VIRE_TARGET_PROCESS_QT_RESOURCES_UIS_AUTO_GEN target_name)
    TARGET_PROCESS_QT_RESOURCES_UIS(${target_name} QT_AUTO_GEN)
ENDMACRO()