// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `DSSDataService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <DSSDataService.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __DSSDataService__DSSServiceCallBack__getName_name = "getName";

const ::std::string __DSSDataService__DSSServiceCallBack__setReuestResult_name = "setReuestResult";

const ::std::string __DSSDataService__DSSService__loginOn_name = "loginOn";

const ::std::string __DSSDataService__DSSService__loginOff_name = "loginOff";

const ::std::string __DSSDataService__DSSService__requestData_name = "requestData";

}
::IceProxy::Ice::Object* ::IceProxy::DSSDataService::upCast(::IceProxy::DSSDataService::DSSServiceCallBack* p) { return p; }

void
::IceProxy::DSSDataService::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::DSSDataService::DSSServiceCallBack>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::DSSDataService::DSSServiceCallBack;
        v->__copyFrom(proxy);
    }
}

::std::string
IceProxy::DSSDataService::DSSServiceCallBack::getName(const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __DSSDataService__DSSServiceCallBack__getName_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__DSSDataService__DSSServiceCallBack__getName_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::DSSDataService::DSSServiceCallBack* __del = dynamic_cast< ::IceDelegate::DSSDataService::DSSServiceCallBack*>(__delBase.get());
            return __del->getName(__ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapperRelaxed(__delBase, __ex, true, __cnt, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::DSSDataService::DSSServiceCallBack::begin_getName(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__DSSDataService__DSSServiceCallBack__getName_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __DSSDataService__DSSServiceCallBack__getName_name, __del, __cookie);
    try
    {
        __result->__prepare(__DSSDataService__DSSServiceCallBack__getName_name, ::Ice::Idempotent, __ctx);
        __result->__writeEmptyParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::std::string
IceProxy::DSSDataService::DSSServiceCallBack::end_getName(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __DSSDataService__DSSServiceCallBack__getName_name);
    ::std::string __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

void
IceProxy::DSSDataService::DSSServiceCallBack::setReuestResult(const ::TaskDataDef::TaskResultDataPtr& resultData, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __DSSDataService__DSSServiceCallBack__setReuestResult_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::DSSDataService::DSSServiceCallBack* __del = dynamic_cast< ::IceDelegate::DSSDataService::DSSServiceCallBack*>(__delBase.get());
            __del->setReuestResult(resultData, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapperRelaxed(__delBase, __ex, true, __cnt, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::DSSDataService::DSSServiceCallBack::begin_setReuestResult(const ::TaskDataDef::TaskResultDataPtr& resultData, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __DSSDataService__DSSServiceCallBack__setReuestResult_name, __del, __cookie);
    try
    {
        __result->__prepare(__DSSDataService__DSSServiceCallBack__setReuestResult_name, ::Ice::Idempotent, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(resultData);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::DSSDataService::DSSServiceCallBack::end_setReuestResult(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __DSSDataService__DSSServiceCallBack__setReuestResult_name);
}

const ::std::string&
IceProxy::DSSDataService::DSSServiceCallBack::ice_staticId()
{
    return ::DSSDataService::DSSServiceCallBack::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::DSSDataService::DSSServiceCallBack::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::DSSDataService::DSSServiceCallBack);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::DSSDataService::DSSServiceCallBack::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::DSSDataService::DSSServiceCallBack);
}

::IceProxy::Ice::Object*
IceProxy::DSSDataService::DSSServiceCallBack::__newInstance() const
{
    return new DSSServiceCallBack;
}
::IceProxy::Ice::Object* ::IceProxy::DSSDataService::upCast(::IceProxy::DSSDataService::DSSService* p) { return p; }

void
::IceProxy::DSSDataService::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::DSSDataService::DSSService>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::DSSDataService::DSSService;
        v->__copyFrom(proxy);
    }
}

bool
IceProxy::DSSDataService::DSSService::loginOn(const ::DSSDataService::DSSServiceCallBackPrx& pxy, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __DSSDataService__DSSService__loginOn_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__DSSDataService__DSSService__loginOn_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::DSSDataService::DSSService* __del = dynamic_cast< ::IceDelegate::DSSDataService::DSSService*>(__delBase.get());
            return __del->loginOn(pxy, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapperRelaxed(__delBase, __ex, true, __cnt, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::DSSDataService::DSSService::begin_loginOn(const ::DSSDataService::DSSServiceCallBackPrx& pxy, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__DSSDataService__DSSService__loginOn_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __DSSDataService__DSSService__loginOn_name, __del, __cookie);
    try
    {
        __result->__prepare(__DSSDataService__DSSService__loginOn_name, ::Ice::Idempotent, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(pxy);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

bool
IceProxy::DSSDataService::DSSService::end_loginOn(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __DSSDataService__DSSService__loginOn_name);
    bool __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

bool
IceProxy::DSSDataService::DSSService::loginOff(const ::DSSDataService::DSSServiceCallBackPrx& pxy, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __DSSDataService__DSSService__loginOff_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__DSSDataService__DSSService__loginOff_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::DSSDataService::DSSService* __del = dynamic_cast< ::IceDelegate::DSSDataService::DSSService*>(__delBase.get());
            return __del->loginOff(pxy, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapperRelaxed(__delBase, __ex, true, __cnt, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::DSSDataService::DSSService::begin_loginOff(const ::DSSDataService::DSSServiceCallBackPrx& pxy, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__DSSDataService__DSSService__loginOff_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __DSSDataService__DSSService__loginOff_name, __del, __cookie);
    try
    {
        __result->__prepare(__DSSDataService__DSSService__loginOff_name, ::Ice::Idempotent, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(pxy);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

bool
IceProxy::DSSDataService::DSSService::end_loginOff(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __DSSDataService__DSSService__loginOff_name);
    bool __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

::TaskDataDef::emRequestResultType
IceProxy::DSSDataService::DSSService::requestData(const ::TaskDataDef::TaskRequestPtr& request, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __DSSDataService__DSSService__requestData_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__DSSDataService__DSSService__requestData_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::DSSDataService::DSSService* __del = dynamic_cast< ::IceDelegate::DSSDataService::DSSService*>(__delBase.get());
            return __del->requestData(request, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapperRelaxed(__delBase, __ex, true, __cnt, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::DSSDataService::DSSService::begin_requestData(const ::TaskDataDef::TaskRequestPtr& request, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__DSSDataService__DSSService__requestData_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __DSSDataService__DSSService__requestData_name, __del, __cookie);
    try
    {
        __result->__prepare(__DSSDataService__DSSService__requestData_name, ::Ice::Idempotent, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(request);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::TaskDataDef::emRequestResultType
IceProxy::DSSDataService::DSSService::end_requestData(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __DSSDataService__DSSService__requestData_name);
    ::TaskDataDef::emRequestResultType __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

const ::std::string&
IceProxy::DSSDataService::DSSService::ice_staticId()
{
    return ::DSSDataService::DSSService::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::DSSDataService::DSSService::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::DSSDataService::DSSService);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::DSSDataService::DSSService::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::DSSDataService::DSSService);
}

::IceProxy::Ice::Object*
IceProxy::DSSDataService::DSSService::__newInstance() const
{
    return new DSSService;
}

::std::string
IceDelegateM::DSSDataService::DSSServiceCallBack::getName(const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __DSSDataService__DSSServiceCallBack__getName_name, ::Ice::Idempotent, __context, __observer);
    __og.writeEmptyParams();
    bool __ok = __og.invoke();
    ::std::string __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

void
IceDelegateM::DSSDataService::DSSServiceCallBack::setReuestResult(const ::TaskDataDef::TaskResultDataPtr& resultData, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __DSSDataService__DSSServiceCallBack__setReuestResult_name, ::Ice::Idempotent, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(resultData);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

bool
IceDelegateM::DSSDataService::DSSService::loginOn(const ::DSSDataService::DSSServiceCallBackPrx& pxy, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __DSSDataService__DSSService__loginOn_name, ::Ice::Idempotent, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(pxy);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    bool __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

bool
IceDelegateM::DSSDataService::DSSService::loginOff(const ::DSSDataService::DSSServiceCallBackPrx& pxy, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __DSSDataService__DSSService__loginOff_name, ::Ice::Idempotent, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(pxy);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    bool __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::TaskDataDef::emRequestResultType
IceDelegateM::DSSDataService::DSSService::requestData(const ::TaskDataDef::TaskRequestPtr& request, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __DSSDataService__DSSService__requestData_name, ::Ice::Idempotent, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(request);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::TaskDataDef::emRequestResultType __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::std::string
IceDelegateD::DSSDataService::DSSServiceCallBack::getName(const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::std::string& __result, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::DSSDataService::DSSServiceCallBack* servant = dynamic_cast< ::DSSDataService::DSSServiceCallBack*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->getName(_current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::std::string& _result;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __DSSDataService__DSSServiceCallBack__getName_name, ::Ice::Idempotent, __context);
    ::std::string __result;
    try
    {
        _DirectI __direct(__result, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

void
IceDelegateD::DSSDataService::DSSServiceCallBack::setReuestResult(const ::TaskDataDef::TaskResultDataPtr& resultData, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::TaskDataDef::TaskResultDataPtr& __p_resultData, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_resultData(__p_resultData)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::DSSDataService::DSSServiceCallBack* servant = dynamic_cast< ::DSSDataService::DSSServiceCallBack*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->setReuestResult(_m_resultData, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::TaskDataDef::TaskResultDataPtr& _m_resultData;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __DSSDataService__DSSServiceCallBack__setReuestResult_name, ::Ice::Idempotent, __context);
    try
    {
        _DirectI __direct(resultData, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

bool
IceDelegateD::DSSDataService::DSSService::loginOn(const ::DSSDataService::DSSServiceCallBackPrx& pxy, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(bool& __result, const ::DSSDataService::DSSServiceCallBackPrx& __p_pxy, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_pxy(__p_pxy)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::DSSDataService::DSSService* servant = dynamic_cast< ::DSSDataService::DSSService*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->loginOn(_m_pxy, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        bool& _result;
        const ::DSSDataService::DSSServiceCallBackPrx& _m_pxy;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __DSSDataService__DSSService__loginOn_name, ::Ice::Idempotent, __context);
    bool __result;
    try
    {
        _DirectI __direct(__result, pxy, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

bool
IceDelegateD::DSSDataService::DSSService::loginOff(const ::DSSDataService::DSSServiceCallBackPrx& pxy, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(bool& __result, const ::DSSDataService::DSSServiceCallBackPrx& __p_pxy, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_pxy(__p_pxy)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::DSSDataService::DSSService* servant = dynamic_cast< ::DSSDataService::DSSService*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->loginOff(_m_pxy, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        bool& _result;
        const ::DSSDataService::DSSServiceCallBackPrx& _m_pxy;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __DSSDataService__DSSService__loginOff_name, ::Ice::Idempotent, __context);
    bool __result;
    try
    {
        _DirectI __direct(__result, pxy, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::TaskDataDef::emRequestResultType
IceDelegateD::DSSDataService::DSSService::requestData(const ::TaskDataDef::TaskRequestPtr& request, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::TaskDataDef::emRequestResultType& __result, const ::TaskDataDef::TaskRequestPtr& __p_request, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_request(__p_request)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::DSSDataService::DSSService* servant = dynamic_cast< ::DSSDataService::DSSService*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->requestData(_m_request, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::TaskDataDef::emRequestResultType& _result;
        const ::TaskDataDef::TaskRequestPtr& _m_request;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __DSSDataService__DSSService__requestData_name, ::Ice::Idempotent, __context);
    ::TaskDataDef::emRequestResultType __result;
    try
    {
        _DirectI __direct(__result, request, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::Object* DSSDataService::upCast(::DSSDataService::DSSServiceCallBack* p) { return p; }

namespace
{
const ::std::string __DSSDataService__DSSServiceCallBack_ids[2] =
{
    "::DSSDataService::DSSServiceCallBack",
    "::Ice::Object"
};

}

bool
DSSDataService::DSSServiceCallBack::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__DSSDataService__DSSServiceCallBack_ids, __DSSDataService__DSSServiceCallBack_ids + 2, _s);
}

::std::vector< ::std::string>
DSSDataService::DSSServiceCallBack::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__DSSDataService__DSSServiceCallBack_ids[0], &__DSSDataService__DSSServiceCallBack_ids[2]);
}

const ::std::string&
DSSDataService::DSSServiceCallBack::ice_id(const ::Ice::Current&) const
{
    return __DSSDataService__DSSServiceCallBack_ids[0];
}

const ::std::string&
DSSDataService::DSSServiceCallBack::ice_staticId()
{
    return __DSSDataService__DSSServiceCallBack_ids[0];
}

::Ice::DispatchStatus
DSSDataService::DSSServiceCallBack::___getName(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Idempotent, __current.mode);
    __inS.readEmptyParams();
    ::std::string __ret = getName(__current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
DSSDataService::DSSServiceCallBack::___setReuestResult(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Idempotent, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::TaskDataDef::TaskResultDataPtr resultData;
    __is->read(resultData);
    __inS.endReadParams();
    setReuestResult(resultData, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __DSSDataService__DSSServiceCallBack_all[] =
{
    "getName",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "setReuestResult"
};

}

::Ice::DispatchStatus
DSSDataService::DSSServiceCallBack::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__DSSDataService__DSSServiceCallBack_all, __DSSDataService__DSSServiceCallBack_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __DSSDataService__DSSServiceCallBack_all)
    {
        case 0:
        {
            return ___getName(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
        case 5:
        {
            return ___setReuestResult(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
DSSDataService::DSSServiceCallBack::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
DSSDataService::DSSServiceCallBack::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
DSSDataService::__patch(DSSServiceCallBackPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::DSSDataService::DSSServiceCallBackPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::DSSDataService::DSSServiceCallBack::ice_staticId(), v);
    }
}

::Ice::Object* DSSDataService::upCast(::DSSDataService::DSSService* p) { return p; }

namespace
{
const ::std::string __DSSDataService__DSSService_ids[2] =
{
    "::DSSDataService::DSSService",
    "::Ice::Object"
};

}

bool
DSSDataService::DSSService::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__DSSDataService__DSSService_ids, __DSSDataService__DSSService_ids + 2, _s);
}

::std::vector< ::std::string>
DSSDataService::DSSService::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__DSSDataService__DSSService_ids[0], &__DSSDataService__DSSService_ids[2]);
}

const ::std::string&
DSSDataService::DSSService::ice_id(const ::Ice::Current&) const
{
    return __DSSDataService__DSSService_ids[0];
}

const ::std::string&
DSSDataService::DSSService::ice_staticId()
{
    return __DSSDataService__DSSService_ids[0];
}

::Ice::DispatchStatus
DSSDataService::DSSService::___loginOn(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Idempotent, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::DSSDataService::DSSServiceCallBackPrx pxy;
    __is->read(pxy);
    __inS.endReadParams();
    bool __ret = loginOn(pxy, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
DSSDataService::DSSService::___loginOff(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Idempotent, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::DSSDataService::DSSServiceCallBackPrx pxy;
    __is->read(pxy);
    __inS.endReadParams();
    bool __ret = loginOff(pxy, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
DSSDataService::DSSService::___requestData(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Idempotent, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::TaskDataDef::TaskRequestPtr request;
    __is->read(request);
    __inS.endReadParams();
    ::TaskDataDef::emRequestResultType __ret = requestData(request, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __DSSDataService__DSSService_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "loginOff",
    "loginOn",
    "requestData"
};

}

::Ice::DispatchStatus
DSSDataService::DSSService::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__DSSDataService__DSSService_all, __DSSDataService__DSSService_all + 7, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __DSSDataService__DSSService_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___loginOff(in, current);
        }
        case 5:
        {
            return ___loginOn(in, current);
        }
        case 6:
        {
            return ___requestData(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
DSSDataService::DSSService::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
DSSDataService::DSSService::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
DSSDataService::__patch(DSSServicePtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::DSSDataService::DSSServicePtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::DSSDataService::DSSService::ice_staticId(), v);
    }
}
