###############################################################################

###############################################################################
SET(OSGPHYSICS_NAME osgphysics)
SET(OSGPHYSICS_DIR $ENV{THIRDPARTY_PATH}/${OSGPHYSICS_NAME})
MESSAGE("******OSGPHYSICS_DIR = ${OSGPHYSICS_DIR}*****")


FIND_PATH(OSGPHYSICS_INCLUDE_DIR osgPhysics/World
PATHS
    ${OSGPHYSICS_DIR}/include
)

###### libraries ######

FIND_LIBRARY(OSGPHYSICS_LIBRARY
  NAMES osgphysics osgPhysics
  PATHS
  "${OSGPHYSICS_DIR}/lib"
)

FIND_LIBRARY(OSGPHYSICS_LIBRARY_DEBUG
  NAMES osgPhysicsd
  PATHS
  "${OSGPHYSICS_DIR}/lib"
)
	  
SET(OSGPHYSICS_FOUND "NO")
IF(OSGPHYSICS_LIBRARY AND OSGPHYSICS_INCLUDE_DIR)
    SET(OSGPHYSICS_FOUND "YES")
ENDIF(OSGPHYSICS_LIBRARY AND OSGPHYSICS_INCLUDE_DIR)

#´ò°ü

	FILE(GLOB ZCHX_OSGPHYSICS_DLL_DEBUG "${OSGPHYSICS_DIR}/bin/*.dll")
	INSTALL(FILES ${ZCHX_OSGPHYSICS_DLL_DEBUG} DESTINATION bin)
	MESSAGE("ZCHX_OSGPHYSICS_DLL_DEBUG = ${ZCHX_OSGPHYSICS_DLL_DEBUG}")
	
	
	
	FILE(GLOB ZCHX_OSGPHYSICS_DLL_RELEASE "${OSGPHYSICS_DIR}/bin/*.dll")
	INSTALL(FILES ${ZCHX_OSGPHYSICS_DLL_RELEASE} DESTINATION bin)
	MESSAGE("ZCHX_OSGPHYSICS_DLL_RELEASE = ${ZCHX_OSGPHYSICS_DLL_RELEASE}")
	

MESSAGE("******Finish FOUND ********")