
SET(LIBTRITON_NAME libTriton)
SET(LIBTRITON_DIR $ENV{LIBTRITON_DIR})
MESSAGE("******LIBTRITON_DIR = ${LIBTRITON_DIR}*****")


FIND_PATH(LIBTRITON_INCLUDE_DIR libTriton/ocean.h
PATHS
    ${LIBTRITON_DIR}/include
	${LIBTRITON_DIR}/include/libTriton
)

###### libraries ######

FIND_LIBRARY(LIBTRITON_LIBRARY
  NAMES ${LIBTRITON_NAME}
  PATHS
  "${LIBTRITON_DIR}/lib"
)

FIND_LIBRARY(LIBTRITON_LIBRARY_DEBUG
  NAMES ${LIBTRITON_NAME}d
  PATHS
  "${LIBTRITON_DIR}/lib"
)
	  
SET(LIBTRITON_FOUND "NO")
IF(LIBTRITON_LIBRARY AND LIBTRITON_INCLUDE_DIR)
    SET(LIBTRITON_FOUND "YES")
ENDIF(LIBTRITON_LIBRARY AND LIBTRITON_INCLUDE_DIR)
