SET(FIND_LIB_NAME XMLSerializer)

FIND_PATH(${FIND_LIB_NAME}_INCLUDE_DIR XmlSerializer.h
PATHS
    $ENV{${FIND_LIB_NAME}_DIR}
)

SET(${FIND_LIB_NAME}_FOUND "NO")
IF(${FIND_LIB_NAME}_INCLUDE_DIR)
    SET(${FIND_LIB_NAME}_FOUND "YES")
ELSE(${FIND_LIB_NAME}_INCLUDE_DIR)
	MESSAGE(FATAL_ERROR "No Find[${FIND_LIB_NAME}] In Enviroment[$ENV{${FIND_LIB_NAME}_DIR}], You Can Set This Parameter By YourSelf")
ENDIF(${FIND_LIB_NAME}_INCLUDE_DIR)
	