
###############################################################################
SET(QGIS_NAME QGIS)
SET(QGIS_DIR $ENV{QGIS_ROOT})
MESSAGE("******QGIS_DIR = ${QGIS_DIR}*****")

MACRO( FIND_QGIS_INCLUDE THIS_QGIS_INCLUDE_DIR THIS_QGIS_INCLUDE_FILE )

FIND_PATH( ${THIS_QGIS_INCLUDE_DIR} ${THIS_QGIS_INCLUDE_FILE}
    PATHS
        ${QGIS_DIR}
    PATH_SUFFIXES
        /include/
)

ENDMACRO( FIND_QGIS_INCLUDE THIS_QGIS_INCLUDE_DIR THIS_QGIS_INCLUDE_FILE )

FIND_QGIS_INCLUDE( QGIS_INCLUDE_DIR qgis.h)

###### libraries ######

MACRO( FIND_QGIS_LIBRARY MYLIBRARY MYLIBRARYNAME )

FIND_LIBRARY(${MYLIBRARY}
    NAMES
        ${MYLIBRARYNAME}
    PATHS
        ${QGIS_DIR}
    PATH_SUFFIXES
        /build/lib/
        /lib/
    
     
        /lib/release/
     )

ENDMACRO(FIND_QGIS_LIBRARY LIBRARY LIBRARYNAME)

FIND_QGIS_LIBRARY( QGIS_CORE_LIBRARY qgis_core )
FIND_QGIS_LIBRARY( QGIS_CORE_LIBRARY_DEBUG qgis_core)

FIND_QGIS_LIBRARY( QGIS_GUI_LIBRARY qgis_gui )
FIND_QGIS_LIBRARY( QGIS_GUI_LIBRARY_DEBUG qgis_gui)

FIND_QGIS_LIBRARY( QGIS_ANALYSIS_LIBRARY qgis_analysis )
FIND_QGIS_LIBRARY( QGIS_ANALYSIS_LIBRARY_DEBUG qgis_analysis)


SET( QGIS_FOUND "NO" )
IF( DTCORE_LIBRARY AND QGIS_INCLUDE_DIR )
    SET( QGIS_FOUND "YES" )
    SET( QGIS_INCLUDE_DIRS ${QGIS_INCLUDE_DIR} )
    GET_FILENAME_COMPONENT( QGIS_LIBRARIES_DIR ${DTCORE_LIBRARY} PATH )
ENDIF( DTCORE_LIBRARY AND QGIS_INCLUDE_DIR )