set(ICE_NAME ice)
SET(ICE_PATH $ENV{ICE_DIR})
MESSAGE("******ICE_PATH = ${ICE_PATH}*****")

FIND_PATH(ICE_INCLUDE_DIR Ice/Ice.h
      PATHS
      ${ICE_PATH}/include)

###### libraries ######

FIND_LIBRARY(ICE_LIBRARY
  NAMES ice
  PATHS
  ${ICE_PATH}/lib)

FIND_LIBRARY(ICE_LIBRARY_DEBUG
NAMES  iced
PATHS
${ICE_PATH}/lib)

SET(ICE_FOUND "NO")
IF(ICE_LIBRARY AND ICE_INCLUDE_DIR)
    SET(ICE_FOUND "YES")
    SET(ICE_INCLUDE_DIRS  ${ICE_INCLUDE_DIR})
ENDIF(ICE_LIBRARY AND ICE_INCLUDE_DIR)

MACRO(FIND_ICE_LIBRARY MYLIBRARY MYLIBRARYNAME)

    FIND_LIBRARY(${MYLIBRARY}
        NAMES ${MYLIBRARYNAME}
        PATHS
        ${ICE_PATH}/lib
    )

ENDMACRO(FIND_ICE_LIBRARY LIBRARY LIBRARYNAME)

# Find release (optimized) libs
FIND_ICE_LIBRARY(icestormservice_LIBRARY icestormservice)
FIND_ICE_LIBRARY(icedb_LIBRARY icedb)
FIND_ICE_LIBRARY(icebox_LIBRARY icebox)
FIND_ICE_LIBRARY(icegrid_LIBRARY icegrid)
FIND_ICE_LIBRARY(icestorm_LIBRARY icestorm)
FIND_ICE_LIBRARY(icepatch2_LIBRARY icepatch2)
FIND_ICE_LIBRARY(icexml_LIBRARY icexml)
FIND_ICE_LIBRARY(icessl_LIBRARY icessl)
FIND_ICE_LIBRARY(iceutil_LIBRARY iceutil)

# Find debug (optimized) libs
FIND_ICE_LIBRARY(icestormservice_LIBRARY_DEBUG icestormserviced)
FIND_ICE_LIBRARY(icedb_LIBRARY_DEBUG icedbd)
FIND_ICE_LIBRARY(icebox_LIBRARY_DEBUG iceboxd)
FIND_ICE_LIBRARY(icegrid_LIBRARY_DEBUG icegridd)
FIND_ICE_LIBRARY(icestorm_LIBRARY_DEBUG icestormd)
FIND_ICE_LIBRARY(icepatch2_LIBRARY_DEBUG icepatch2d)
FIND_ICE_LIBRARY(icexml_LIBRARY_DEBUG icexmld)
FIND_ICE_LIBRARY(icessl_LIBRARY_DEBUG icessld)
FIND_ICE_LIBRARY(iceutil_LIBRARY_DEBUG iceutild)

#打包
IF(CMAKE_BUILD_TYPE MATCHES Debug)
    FILE(GLOB ZCHX_ICE_DLL_DEBUG "${ICE_PATH}/bin/debug/*.dll")
    INSTALL(FILES ${ZCHX_ICE_DLL_DEBUG} DESTINATION bin)
    
ELSE(CMAKE_BUILD_TYPE MATCHES Debug)

    FILE(GLOB ZCHX_ICE_DLL_RELEASE "${ICE_PATH}/bin/release/*.dll")
    INSTALL(FILES ${ZCHX_ICE_DLL_RELEASE} DESTINATION bin)
    
ENDIF(CMAKE_BUILD_TYPE MATCHES Debug)
