SET(XMLFOUNDATION_LIB_NAME XMLFOUNDATION)
SET(XMLFOUNDATION_HOME $ENV{XMLFOUNDATION_ROOT})

FIND_PATH(XMLFOUNDATION_INCLUDE_DIR XMLFoundation.h
PATHS
    ${XMLFOUNDATION_HOME}/include
)
###### libraries ######

FIND_LIBRARY(XMLFOUNDATION_LIBRARY
  NAMES ${XMLFOUNDATION_LIB_NAME}
  PATHS
  "${XMLFOUNDATION_HOME}/lib"
)

FIND_LIBRARY(XMLFOUNDATION_LIBRARY_DEBUG
  NAMES ${XMLFOUNDATION_LIB_NAME}d
  PATHS
  "${XMLFOUNDATION_HOME}/lib"
)
	  
SET(XMLFOUNDATION_FOUND "NO")
IF(XMLFOUNDATION_LIBRARY AND XMLFOUNDATION_INCLUDE_DIR)
    SET(XMLFOUNDATION_FOUND "YES")
ENDIF(XMLFOUNDATION_LIBRARY AND XMLFOUNDATION_INCLUDE_DIR)


IF (XMLFOUNDATION_LIBRARY)
  SET(XMLFOUNDATION_LIBRARIES ${XMLFOUNDATION_LIBRARY})
ENDIF (XMLFOUNDATION_LIBRARY)