
###############################################################################
SET(OSG_NAME osgEarth)
#SET(OSGEARTH_DIR $ENV{OSGEARTH_ROOT})
SET(OSGEARTH_BIN_PATH ${OSGEARTH_DIR}/bin)


MACRO( FIND_OSGEARTH_INCLUDE THIS_OSGEARTH_INCLUDE_DIR THIS_OSGEARTH_INCLUDE_FILE )

FIND_PATH( ${THIS_OSGEARTH_INCLUDE_DIR} ${THIS_OSGEARTH_INCLUDE_FILE}
    PATHS
        ${OSGEARTH_DIR}
    PATH_SUFFIXES
        /include/
)

if(${THIS_OSGEARTH_INCLUDE_DIR})
    mark_as_advanced(${THIS_OSGEARTH_INCLUDE_DIR})
endif()

ENDMACRO( FIND_OSGEARTH_INCLUDE THIS_OSGEARTH_INCLUDE_DIR THIS_OSGEARTH_INCLUDE_FILE )

FIND_OSGEARTH_INCLUDE( OSGEARTH_INCLUDE_DIR osgEarth/Common)

###### libraries ######

MACRO( FIND_OSGEARTH_LIBRARY MYLIBRARY MYLIBRARYNAME )

    FIND_LIBRARY(${MYLIBRARY}
        NAMES
            ${MYLIBRARYNAME}
        PATHS
            ${OSGEARTH_DIR}
        PATH_SUFFIXES
                /lib/
            /lib/debug/
            /lib/release/
         )
    if(${MYLIBRARY})
        mark_as_advanced(${MYLIBRARY})
    endif()
ENDMACRO(FIND_OSGEARTH_LIBRARY LIBRARY LIBRARYNAME)

FIND_OSGEARTH_LIBRARY( OSGDB_OSGEARTH_FEATURE_OGR_LIBRARY osgdb_osgearth_feature_ogr )
FIND_OSGEARTH_LIBRARY( OSGDB_OSGEARTH_FEATURE_OGR_LIBRARY_DEBUG osgdb_osgearth_feature_ogrd)

FIND_OSGEARTH_LIBRARY( OSGDB_OSGEARTH_FEATURE_TFS_LIBRARY osgdb_osgearth_feature_tfs )
FIND_OSGEARTH_LIBRARY( OSGDB_OSGEARTH_FEATURE_TFS_LIBRARY_DEBUG osgdb_osgearth_feature_tfsd)

FIND_OSGEARTH_LIBRARY( OSGDB_OSGEARTH_FEATURE_WFS_LIBRARY osgdb_osgearth_feature_wfs )
FIND_OSGEARTH_LIBRARY( OSGDB_OSGEARTH_FEATURE_WFS_LIBRARY_DEBUG osgdb_osgearth_feature_wfsd)

FIND_OSGEARTH_LIBRARY( OSGDB_OSGEARTH_LIBRARY osgdb_osgearth_gdal )
FIND_OSGEARTH_LIBRARY( OSGDB_OSGEARTH_LIBRARY_DEBUG osgdb_osgearth_gdald )

FIND_OSGEARTH_LIBRARY( OSGEARTH_LIBRARY osgEarth )
FIND_OSGEARTH_LIBRARY( OSGEARTH_LIBRARY_DEBUG osgEarthd )

FIND_OSGEARTH_LIBRARY( OSGEARTHQT_LIBRARY osgEarthQt )
FIND_OSGEARTH_LIBRARY( OSGEARTHQT_LIBRARY_DEBUG osgEarthQtd )

FIND_OSGEARTH_LIBRARY( OSGEARTHANNOTATION_LIBRARY osgEarthAnnotation )
FIND_OSGEARTH_LIBRARY( OSGEARTHANNOTATION_LIBRARY_DEBUG osgEarthAnnotationd )

FIND_OSGEARTH_LIBRARY( OSGEARTHFEATURES_LIBRARY osgEarthFeatures )
FIND_OSGEARTH_LIBRARY( OSGEARTHFEATURES_LIBRARY_DEBUG osgEarthFeaturesd )

FIND_OSGEARTH_LIBRARY( OSGEARTHSYMBOLOGY_LIBRARY osgEarthSymbology )
FIND_OSGEARTH_LIBRARY( OSGEARTHSYMBOLOGY_LIBRARY_DEBUG osgEarthSymbologyd )

FIND_OSGEARTH_LIBRARY( OSGEARTHUTIL_LIBRARY osgEarthUtil )
FIND_OSGEARTH_LIBRARY( OSGEARTHUTIL_LIBRARY_DEBUG osgEarthUtild )

SET( OSGEARTH_FOUND "NO" )
IF( OSGEARTH_LIBRARY AND OSGEARTH_INCLUDE_DIR )
    SET( OSGEARTH_FOUND "YES" )
    SET( OSGEARTH_INCLUDE_DIRS ${OSGEARTH_INCLUDE_DIR} )
    GET_FILENAME_COMPONENT( OSGEARTH_LIBRARIES_DIR ${OSGEARTH_LIBRARY} PATH )
ENDIF( OSGEARTH_LIBRARY AND OSGEARTH_INCLUDE_DIR )


FILE(GLOB ${APPLICATION_NAME}_DLL "${OSGEARTH_BIN_PATH}/*.dll")
INSTALL(FILES ${${APPLICATION_NAME}_DLL} DESTINATION bin)