
SET(CERTI_NAME CERTI)
SET(CERTI_DIR $ENV{CERTI_ROOT})

MACRO( FIND_CERTI_INCLUDE THIS_CERTI_INCLUDE_DIR THIS_CERTI_INCLUDE_FILE )

FIND_PATH(CERTI_INCLUDE_DIR RTI.hh
PATHS
    ${CERTI_DIR}/include
	${CERTI_DIR}/include/CERTI
#zq
	$ENV{CERTI_ROOT}/include
	$ENV{CERTI_ROOT}/libCERTI
	$ENV{CERTI_ROOT}/libHLA
	$ENV{CERTI_ROOT}/libRTI
	$ENV{CERTI_ROOT}
)

ENDMACRO( FIND_CERTI_INCLUDE THIS_CERTI_INCLUDE_DIR THIS_CERTI_INCLUDE_FILE )


###### libraries ######

MACRO( FIND_CERTI_LIBRARY MYLIBRARY MYLIBRARYNAME )

FIND_LIBRARY(${MYLIBRARY}
    NAMES
        ${MYLIBRARYNAME}
    PATHS
        ${CERTI_DIR}
    PATH_SUFFIXES
		/build/lib/
		/lib/
	
        /lib/debug/
        /lib/release/
     )

ENDMACRO(FIND_CERTI_LIBRARY LIBRARY LIBRARYNAME)


FIND_CERTI_LIBRARY( CERTI_LIBRARY CERTI)
FIND_CERTI_LIBRARY( CERTI_LIBRARY_DEBUG CERTId)

FIND_CERTI_LIBRARY( FEDTIME_LIBRARY FedTime )
FIND_CERTI_LIBRARY( FEDTIME_LIBRARY_DEBUG FedTimed)

FIND_CERTI_LIBRARY( FEDTIME1516_LIBRARY FedTime1516 )
FIND_CERTI_LIBRARY( FEDTIME1516_LIBRARY FedTime1516d)

FIND_CERTI_LIBRARY( GRAPH_LIBRARY graph )
FIND_CERTI_LIBRARY( GRAPH_LIBRARY_LIBRARY_DEBUG graphd)

FIND_CERTI_LIBRARY( HLA_LIBRARY HLA )
FIND_CERTI_LIBRARY( HLA_LIBRARY_DEBUG HLAd)

FIND_CERTI_LIBRARY( RTI1516_LIBRARY RTI1516 )
FIND_CERTI_LIBRARY( RTI1516_LIBRARY_DEBUG RTI1516d)

FIND_CERTI_LIBRARY( RTING_LIBRARY RTI-NG )
FIND_CERTI_LIBRARY( RTING_LIBRARY_DEBUG RTI-NGd)
	  
SET(CERTI_FOUND "NO")
IF(CERTI_LIBRARY AND CERTI_INCLUDE_DIR)
    SET(CERTI_FOUND "YES")
ENDIF(CERTI_LIBRARY AND CERTI_INCLUDE_DIR)
