

include(macro_adapter_matching_libname_includedir)
###############################################################################
SET(DELTA3D_NAME delta3d)

MACRO( FIND_DELTA3D_INCLUDE THIS_DELTA3D_INCLUDE_DIR THIS_DELTA3D_INCLUDE_FILE )

    FIND_PATH( ${THIS_DELTA3D_INCLUDE_DIR} ${THIS_DELTA3D_INCLUDE_FILE}
        PATHS
            ${DELTA3D_DIR}
            ${DELTA3D_ROOT}
            $ENV{DELTA3D_DIR}
            $ENV{DELTA3D_ROOT}
        PATH_SUFFIXES
            /include/
    )
    if(${THIS_DELTA3D_INCLUDE_DIR})
        mark_as_advanced(${THIS_DELTA3D_INCLUDE_DIR})
    endif()

ENDMACRO( FIND_DELTA3D_INCLUDE THIS_DELTA3D_INCLUDE_DIR THIS_DELTA3D_INCLUDE_FILE )


###### libraries ######

MACRO( FIND_DELTA3D_LIBRARY MYLIBRARY MYLIBRARYNAME )

FIND_LIBRARY(${MYLIBRARY}
    NAMES
        ${MYLIBRARYNAME}
    PATHS
        ${DELTA3D_DIR}
        ${DELTA3D_ROOT}
        $ENV{DELTA3D_DIR}
        $ENV{DELTA3D_ROOT}
    PATH_SUFFIXES
        /build/lib/
        /lib/
    
        /lib/debug/
        /lib/release/
     )
    if(${MYLIBRARY})
        mark_as_advanced(${MYLIBRARY})
    endif()
ENDMACRO(FIND_DELTA3D_LIBRARY LIBRARY LIBRARYNAME)

FIND_PACKAGE(ODE REQUIRED) #must be finded before the DELTA3D


FIND_DELTA3D_INCLUDE( DELTA3D_INCLUDE_DIR dtCore/base.h)
SET(DTCORE_INCLUDE_DIR ${DELTA3D_INCLUDE_DIR})

FIND_DELTA3D_LIBRARY( DELTA3D_DTCORE_LIBRARY dtCore )
FIND_DELTA3D_LIBRARY( DELTA3D_DTCORE_LIBRARY_DEBUG dtCored )

FIND_DELTA3D_LIBRARY( DELTA3D_DTGAME_LIBRARY dtGame )
FIND_DELTA3D_LIBRARY( DELTA3D_DTGAME_LIBRARY_DEBUG dtGamed )

FIND_DELTA3D_LIBRARY( DELTA3D_DTUTIL_LIBRARY dtUtil )
FIND_DELTA3D_LIBRARY( DELTA3D_DTUTIL_LIBRARY_DEBUG dtUtild )

FIND_DELTA3D_LIBRARY( DELTA3D_DTABC_LIBRARY dtABC )
FIND_DELTA3D_LIBRARY( DELTA3D_DTABC_LIBRARY_DEBUG dtABCd)

FIND_DELTA3D_LIBRARY( DELTA3D_DTACTOR_LIBRARY dtActors )
FIND_DELTA3D_LIBRARY( DELTA3D_DTACTOR_LIBRARY_DEBUG dtActorsd)

FIND_DELTA3D_LIBRARY( DELTA3D_DTANIM_LIBRARY dtAnim )
FIND_DELTA3D_LIBRARY( DELTA3D_DTANIM_LIBRARY_DEBUG dtAnimd)

FIND_DELTA3D_LIBRARY( DELTA3D_DTAUDIO_LIBRARY dtAudio )
FIND_DELTA3D_LIBRARY( DELTA3D_DTAUDIO_LIBRARY_DEBUG dtAudiod)

FIND_DELTA3D_LIBRARY( DELTA3D_DTPHYSICS_LIBRARY dtPhysics )
FIND_DELTA3D_LIBRARY( DELTA3D_DTPHYSICS_LIBRARY_DEBUG dtPhysicsd)

FIND_DELTA3D_LIBRARY( DELTA3D_DTGUI_LIBRARY dtGUI )
FIND_DELTA3D_LIBRARY( DELTA3D_DTGUI_LIBRARY_DEBUG dtGUId)

FIND_DELTA3D_LIBRARY( DELTA3D_DTNET_LIBRARY dtNet )
FIND_DELTA3D_LIBRARY( DELTA3D_DTNET_LIBRARY_DEBUG dtNetd)

FIND_DELTA3D_LIBRARY( DELTA3D_DTNETGM_LIBRARY dtNetGM )
FIND_DELTA3D_LIBRARY( DELTA3D_DTNETGM_LIBRARY_DEBUG dtNetGMd)

SET(DTCORE_LIBRARY ${DELTA3D_DTCORE_LIBRARY})
SET(DTCORE_LIBRARY_DEBUG ${DELTA3D_DTCORE_LIBRARY_DEBUG})

SET(DTGAME_LIBRARY ${DELTA3D_DTGAME_LIBRARY})
SET(DTGAME_LIBRARY_DEBUG ${DELTA3D_DTGAME_LIBRARY_DEBUG})

SET(DTUTIL_LIBRARY ${DELTA3D_DTUTIL_LIBRARY})
SET(DTUTIL_LIBRARY_DEBUG ${DELTA3D_DTUTIL_LIBRARY_DEBUG})

SET(DTABC_LIBRARY ${DELTA3D_DTABC_LIBRARY})
SET(DTABC_LIBRARY_DEBUG ${DELTA3D_DTABC_LIBRARY_DEBUG})

SET(DTACTOR_LIBRARY ${DELTA3D_DTACTOR_LIBRARY})
SET(DTACTOR_LIBRARY_DEBUG ${DELTA3D_DTACTOR_LIBRARY_DEBUG})

SET(DTANIM_LIBRARY ${DELTA3D_DTANIM_LIBRARY})
SET(DTANIM_LIBRARY_DEBUG ${DELTA3D_DTANIM_LIBRARY_DEBUG})

SET(DTAUDIO_LIBRARY ${DELTA3D_DTAUDIO_LIBRARY})
SET(DTAUDIO_LIBRARY_DEBUG ${DELTA3D_DTAUDIO_LIBRARY_DEBUG})

SET(DTPHYSICS_LIBRARY ${DELTA3D_DTPHYSICS_LIBRARY})
SET(DTPHYSICS_LIBRARY_DEBUG ${DELTA3D_DTPHYSICS_LIBRARY_DEBUG})

SET(DTGUI_LIBRARY ${DELTA3D_DTGUI_LIBRARY})
SET(DTGUI_LIBRARY_DEBUG ${DELTA3D_DTGUI_LIBRARY_DEBUG})

SET(DTNET_LIBRARY ${DELTA3D_DTNET_LIBRARY})
SET(DTNET_LIBRARY_DEBUG ${DELTA3D_DTNET_LIBRARY_DEBUG})

SET(DTNETGM_LIBRARY ${DELTA3D_DTNETGM_LIBRARY})
SET(DTNETGM_LIBRARY_DEBUG ${DELTA3D_DTNETGM_LIBRARY_DEBUG})

SET( DELTA3D_FOUND "NO" )
IF( DELTA3D_DTCORE_LIBRARY AND DELTA3D_INCLUDE_DIR )
    SET( DELTA3D_FOUND "YES" )
    SET( DELTA3D_INCLUDE_DIRS ${DELTA3D_INCLUDE_DIR} )
    GET_FILENAME_COMPONENT( DELTA3D_LIBRARIES_DIR ${DELTA3D_DTCORE_LIBRARY} PATH )
ENDIF( DELTA3D_DTCORE_LIBRARY AND DELTA3D_INCLUDE_DIR )