# Locate CEGUI
# This module defines
# CEGUI_LIBRARY
# CEGUI_FOUND, if false, do not try to link to CEGUI
# CEGUI_INCLUDE_DIR, where to find the headers
#
# $CEGUI_DIR is an environment variable that would
# correspond to the ./configure --prefix=$CEGUI_DIR
#
# Created by David Guthrie with code from Robert Osfield. 
set(THIS_LIB_DEPEND_NAME CEGUI)

GET_DEPENDS_DIR(${THIS_LIB_DEPEND_NAME} ${THIS_LIB_DEPEND_NAME}_SEARCH_FOLDERS)
MESSAGE(STATUS "FOLDERS:${${THIS_LIB_DEPEND_NAME}_SEARCH_FOLDERS}")

include(util.common_find_path)
COMMON_FIND_PATH_NORMAL(${THIS_LIB_DEPEND_NAME}
    CEGUI/CEGUI.h
PATHS
    ${${THIS_LIB_DEPEND_NAME}_SEARCH_FOLDERS}
)

include(util.common_find_library)
SET(CEGUIList CEGUIBase CEGUI)
COMMON_FIND_LIBARAY_NORMAL(
    ${THIS_LIB_DEPEND_NAME}_LIBRARY
    ${THIS_LIB_DEPEND_NAME}
    "${CEGUIList}"  
    VERSIONED_LIB
)

SET(CEGUIDebugList CEGUIBase_d)
COMMON_FIND_LIBARAY_NORMAL(
    ${THIS_LIB_DEPEND_NAME}_LIBRARY_DEBUG 
    ${THIS_LIB_DEPEND_NAME}
    "${CEGUIDebugList}"
    VERSIONED_LIB
    DEBUG_MSG
)

SET(CEGUIOGLList CEGUIOpenGLRenderer)
COMMON_FIND_LIBARAY_NORMAL(
    CEGUIOPENGL_LIBRARY 
    CEGUIOPENGL 
    "${CEGUIOGLList}"
PATHS
    ${${THIS_LIB_DEPEND_NAME}_SEARCH_FOLDERS}
VERSIONED_LIB
DEBUG_MSG
)

SET(CEGUIOGLDebugList CEGUIOpenGLRenderer_d)
COMMON_FIND_LIBARAY_NORMAL(
    CEGUIOPENGL_LIBRARY_DEBUG 
    CEGUIOPENGL 
    "${CEGUIOGLDebugList}"
PATHS
    ${${THIS_LIB_DEPEND_NAME}_SEARCH_FOLDERS}
VERSIONED_LIB
)


#验证变量合法
include(macro_find_package_handle_standard_args)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
	${THIS_LIB_DEPEND_NAME} 
	DEFAULT_MSG
	${THIS_LIB_DEPEND_NAME}_LIBRARY 
	${THIS_LIB_DEPEND_NAME}_INCLUDE_DIR 
    ${THIS_LIB_DEPEND_NAME}_LIBRARY_DEBUG
)

IF (${THIS_LIB_DEPEND_NAME}_FOUND)
   IF (NOT ${THIS_LIB_DEPEND_NAME}_FIND_QUIETLY)
      MESSAGE(STATUS "Found ${THIS_LIB_DEPEND_NAME}: ${${THIS_LIB_DEPEND_NAME}_LIBRARY}")
   ENDIF (NOT ${THIS_LIB_DEPEND_NAME}_FIND_QUIETLY)
ELSE (${THIS_LIB_DEPEND_NAME}_FOUND)
   IF (${THIS_LIB_DEPEND_NAME}_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find ${THIS_LIB_DEPEND_NAME}")
   ENDIF (${THIS_LIB_DEPEND_NAME}_FIND_REQUIRED)
ENDIF (${THIS_LIB_DEPEND_NAME}_FOUND)

if(${THIS_LIB_DEPEND_NAME}_FOUND)
	set(${THIS_LIB_DEPEND_NAME}_LIBRARIES ${${THIS_LIB_DEPEND_NAME}_LIBRARY_DEBUG} ${${THIS_LIB_DEPEND_NAME}_LIBRARY})
	
	include(util.common_make_import_target)
	COMMON_MAKE_IMPORT_TARGET(${THIS_LIB_DEPEND_NAME} 
		${${THIS_LIB_DEPEND_NAME}_INCLUDE_DIR}
		${${THIS_LIB_DEPEND_NAME}_LIBRARY_DEBUG}
		${${THIS_LIB_DEPEND_NAME}_LIBRARY}
    )
    
    # COMMON_MAKE_IMPORT_TARGET_BASE(
    #     ${THIS_LIB_DEPEND_NAME} 
    #     CEGUIOPENGL
	# 	${${THIS_LIB_DEPEND_NAME}_INCLUDE_DIR}
	# 	${CEGUIOPENGL_LIBRARY_DEBUG}
	# 	${CEGUIOPENGL_LIBRARY}
	# )

	mark_as_advanced(
		${THIS_LIB_DEPEND_NAME}_INCLUDE_DIR
		${THIS_LIB_DEPEND_NAME}_LIBRARY
		${THIS_LIB_DEPEND_NAME}_LIBRARY_DEBUG
	)
endif()