include(util.common_error)
include(util.common_print_properties)
include(util.common_check_debug)
include(util.common_assert)
include(util.common_correct_path)
include(util.common_get_env)
include(util.common_parse_arguments)
include(util.common_upper_list_string)
include(util.common_list_subdirectories)
include(util.common_append_target_property)
include(util.common_make_import_target)
include(util.common_search_target_files)
include(util.common_get_library_dir_info)
include(util.common_get_library_folder)
include(util.common_source_group)
include(util.common_list_contains)
include(util.common_set_depends_dir)
include(util.common_add_library)


include(util.common_find_package)
include(util.common_add_target_runtime_depends)